language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

notifications:
  email: false

git:
  depth: 1

install:
  - make install

script:
  - make test

after_success:
  - make coverage
